title: Cambridge iGCSE English Resources (0500/0990 & 0475/0992/2010)
description: High-quality searchable PDFs of official Cambridge IGCSE coursebooks, workbooks & teacher guides for 0500/0990 and 0475/0992/2010. Instant delivery for homeschoolers, tutors & international schools.
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme

# Optional customizations for Primer theme
show_downloads: false
