title: Cambridge iGCSE English Resources (0500/0990 & 0475/0992/2010)
description: High-quality digitized Cambridge IGCSE English PDFs for 2027 syllabus
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme

# Optional customizations for Primer theme
show_downloads: false
